name: Animation
version: '${project.version}'
main: dk.banannus.crates.Crates
api-version: 1.19
authors: [ Banannus ]
description: ArmorStand Animations
commands:
  animation:
    description: Test command til animationer
